name: Deploy PocketBase

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Fly
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy PocketBase
        run: flyctl deploy --remote-only --app spendly-pocketbase
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
